### ISSUE TITLE
Empty Lines - Remove extraneous tabs / spaces

### ISSUE THREAD

**Issue by lewishowles** [MiguelCastillo/Brackets-wsSanitizer#14]
I'm not sure if this is supposed to already happen or not, but it doesn't seem to in my current project.

As we know if we leave spaces to separate our code, Brackets will tab these into the current indentation level.

I'd love for all of those tabs on lines that contain no code to be removed.

**Comment by MiguelCastillo** [comment]
@lewishowles Yeah sanitizer will trim any line that only has spaces/tabs.

**Comment by MiguelCastillo** [comment]
@lewishowles I am closing this one. Let me know if you have more questions.
