### ISSUE TITLE
Sanitizer stops working after running one or more times

### ISSUE THREAD

**Issue by onetrev** [MiguelCastillo/Brackets-wsSanitizer#15]
Sorry if I'm missing something, but does this extension also apply to .js files? Seems to be working perfectly on my .php files but nothing happens on the few .js files I've tried so far. Thank you!

**Comment by MiguelCastillo** [comment]
@onetrev yeah for sure, it should be working with js files.  Can you explain a bit what you are converting?  Is your file using tabs and you are converting to spaces... Or vise versa?

**Comment by onetrev** [comment]
My bad, it's not .js files specifically that is the issue. After further checking with fresh eyes, sanitizing works great on first load of Brackets. It'll always fire at least once. Sometimes it will do more files as I go, but then suddenly it just stops. From then on, no files will be sanitized. I can switch projects, load a multitude of different files, but nothing happens. If I *close* and reload Brackets, it's back to working again every single time. But I never get more than maybe 3 or 4 files until it stops.

The big issue is I can't seem to determine what causes the issue and worst of all no errors show in the Brackets console. Which is not very helpful I know. I've run through testing this at least 6-8 times, and this is definitely happening every time within the 3 or 4 file limit, sometimes after only 1 file being sanitized.

The files I'm testing this is are using tabs, and converting to spaces (which is my default Brackets setting).

Any other info I can provide to help, let me know!

**Comment by MiguelCastillo** [comment]
@onetrev yeah I just reproduced this issue. just randomly happened.  I don't have steps to reproduce it but I will definitely keep an eye on it.

**Comment by MiguelCastillo** [comment]
@onetrev ok, so when I saw this issue happen I had a legit bug while I was implementing a new feature... So I don't think it is the same issue as yours.  Can you do me a favor?  Can you install wsSanitizer from master and see if the issue occurs?  If it occurs, let me know and I am will setup some debugging to see if we can fix this issue...

I have added a bit of logic to add/release references to the document to make sure we don't run into issues while operating on the document.  Hopefully this will help your issue.

**Comment by onetrev** [comment]
Done. I installed by using the [repo URL](https://github.com/MiguelCastillo/Brackets-wsSanitizer), that should do it right?

After I cleared out the "Working Files" in my project I'm using to test this all seems to be going better. I will let you know if I see a glitch again over the next few days or real working. Thanks!!

**Comment by MiguelCastillo** [comment]
@onetrev yeah that's how you install it form the repo :)   Keep me posted, please.

**Comment by MiguelCastillo** [comment]
@onetrev One thing I have noticed is that code folding is definitely having issues causing save events to no longer trigger.  I had to disable code folding...  I figured I shared that with you in case you run into the issue.  Maybe you can disable code folding to help me test this.

**Comment by onetrev** [comment]
Interesting. Are you talking about the built in code folding in the latest Brackets (1.3) or the extension? Since 1.3 I've removed the extension and gone with the built-in.

**Comment by MiguelCastillo** [comment]
The built in...  The issue is more easily reproduce when sanitizing a document with collapsed sections.

**Comment by onetrev** [comment]
Actually I think the issue for me might have been documents with mixed tabs and spaces. I just updated to the latest version of wsSanitizer and is see this notification appearing now on files that previously didn't sanitize. Could that be it as with out without code folding I can no longer reproduce this?

**Comment by MiguelCastillo** [comment]
do you have jsdocs in your code?

**Comment by onetrev** [comment]
No. But I do have https://github.com/wikunia/brackets-funcdocr installed, which is basically the same thing I think.

Just to ensure clarity though, I want to repeat that I am able to sanitize all whitespace now with latest update to your extension.

Only thing that is a bit off is for files that are nicely sanitized, using spaces for indent, if I leave a few hanging spaces at an end of a line for example it doesn't sanitize on save. Instead if I switch to another file then back to the original file I will get the notification about "mixed tabs and spaces" and that will then allow me to sanitize.

Sorry this has been a long issue to solve!

**Comment by MiguelCastillo** [comment]
I found the issue with tabs not properly detecting when the line has mixed spaces, that should not be processed.  This is common for jsdocs where the comments are indented one space...  So technically that should trigger a sanitize, but in practice it should leave that alone.  I made changes I will be pushing out shortly.  This is a separate issue though.

**Comment by MiguelCastillo** [comment]
https://github.com/MiguelCastillo/Brackets-wsSanitizer/pull/24

**Comment by MiguelCastillo** [comment]
@onetrev no problem at all!  I appreciate you helping me.  :)

**Comment by MiguelCastillo** [comment]
@onetrev I am not sure if this issue is still happening for you. Do you think you could verify?

**Comment by onetrev** [comment]
Darn, wish I could sorry. I got frustrated with Brackets and various little issues I had with some extensions, so I actually moved on to Atom (and love it!). Thanks so much for following up, I guess for now just close this issue hey?
