### ISSUE TITLE
Newline at the end of the file configurable

### ISSUE THREAD

**Issue by kadza** [MiguelCastillo/Brackets-wsSanitizer#21]
Hi,

I didn't find a configuration option for adding newline at the end of the file. 
Is it there?
Do you plan to add it?

**Comment by MiguelCastillo** [comment]
@kadza Are you trying to disable adding a newline?

**Comment by MiguelCastillo** [comment]
alright, added the ability to enable/disable processing new lines. https://github.com/MiguelCastillo/Brackets-wsSanitizer/pull/22

https://github.com/MiguelCastillo/Brackets-wsSanitizer#options

**Comment by kadza** [comment]
Works like a charm. Thx
