### ISSUE TITLE
Ability to exclude file types

### ISSUE THREAD

**Issue by terraconnect** [MiguelCastillo/Brackets-wsSanitizer#29]
As a possible enhancement, it would be great to be able to exclude certain file types, where line ending spaces are of importance. I think for example of markdown, where extra ending spaces are used for line breaks.

Thanks anyway for this extension.

**Comment by MiguelCastillo** [comment]
Hi, do you think this would help?  https://github.com/MiguelCastillo/Brackets-wsSanitizer#bracketsjson-with-language-settings

**Comment by terraconnect** [comment]
@MiguelCastillo Sorry for the disturbance...
That definitly helps. :)

**Comment by MiguelCastillo** [comment]
no disturbance at all! :)  glad it helps
