### ISSUE TITLE
Behaviour regarding existing whitespace?

### ISSUE THREAD

**Issue by joepie91** [MiguelCastillo/Brackets-wsSanitizer#4]
It doesn't become entirely clear from the README how this extension treats existing whitespace in a document. Brackets itself seems to auto-detect the existing spacing of a document and adjust its per-file configuration accordingly, so now I'm wondering which of the two this extension does:

1. Does it also detect the per-file spacing, and adjust anything in the file that doesn't match that?
2. Or does it completely ignore the per-file spacing, and blindly apply the user preference to every file that is saved, no matter what the spacing was beforehand?

If it's the latter, that'd cause a problem with projects where the whitespace style may not match that of an individual developer.

**Comment by PhiLhoSoft** [comment]
Apparently the PR has been merged, perhaps you should close this issue...

Suggestion: for newbies like me, a link to https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences might be nice. Indicating these settings can be adjusted per language or per file can be useful too (the Bracket doc is a bit terse / alluding on the topic).

**Comment by MiguelCastillo** [comment]
@PhiLhoSoft yeah this is a great idea.  I will put something together for this.

**Comment by MiguelCastillo** [comment]
@PhiLhoSoft  I just added some details Brackets preferences. Please feel free to report new issue or even better, submit a PR :)

**Comment by MiguelCastillo** [comment]
https://github.com/MiguelCastillo/Brackets-wsSanitizer/commit/513bed70ecafa0418887fe6b01088b59a88402c2

**Comment by PhiLhoSoft** [comment]
Great! Well done.
